# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.4_1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.4_1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/ssbug20 1/Desktop/work/bluster_cache"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/ssbug20 1/Desktop/work/bluster_cache"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.4_1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.9.4_1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/ssbug20 1/Desktop/work/bluster_cache/CMakeFiles" "/Users/ssbug20 1/Desktop/work/bluster_cache/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/ssbug20 1/Desktop/work/bluster_cache/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named src

# Build rule for target.
src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 src
.PHONY : src

# fast build rule for target.
src/fast:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/build
.PHONY : src/fast

cache.o: cache.cpp.o

.PHONY : cache.o

# target to build an object file
cache.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/cache.cpp.o
.PHONY : cache.cpp.o

cache.i: cache.cpp.i

.PHONY : cache.i

# target to preprocess a source file
cache.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/cache.cpp.i
.PHONY : cache.cpp.i

cache.s: cache.cpp.s

.PHONY : cache.s

# target to generate assembly for a file
cache.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/cache.cpp.s
.PHONY : cache.cpp.s

kqueue_server.o: kqueue_server.cpp.o

.PHONY : kqueue_server.o

# target to build an object file
kqueue_server.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/kqueue_server.cpp.o
.PHONY : kqueue_server.cpp.o

kqueue_server.i: kqueue_server.cpp.i

.PHONY : kqueue_server.i

# target to preprocess a source file
kqueue_server.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/kqueue_server.cpp.i
.PHONY : kqueue_server.cpp.i

kqueue_server.s: kqueue_server.cpp.s

.PHONY : kqueue_server.s

# target to generate assembly for a file
kqueue_server.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/kqueue_server.cpp.s
.PHONY : kqueue_server.cpp.s

server_init.o: server_init.cpp.o

.PHONY : server_init.o

# target to build an object file
server_init.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/server_init.cpp.o
.PHONY : server_init.cpp.o

server_init.i: server_init.cpp.i

.PHONY : server_init.i

# target to preprocess a source file
server_init.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/server_init.cpp.i
.PHONY : server_init.cpp.i

server_init.s: server_init.cpp.s

.PHONY : server_init.s

# target to generate assembly for a file
server_init.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/server_init.cpp.s
.PHONY : server_init.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... src"
	@echo "... cache.o"
	@echo "... cache.i"
	@echo "... cache.s"
	@echo "... kqueue_server.o"
	@echo "... kqueue_server.i"
	@echo "... kqueue_server.s"
	@echo "... server_init.o"
	@echo "... server_init.i"
	@echo "... server_init.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

